[package]
name = "beaver_social"
edition = "2024.beta"
license = "UNLICENSED"
authors = ["Spandan Barve (contact@marsian.dev)"]

[addresses]
beaver_social = "0x0"

[dependencies]
# MoveStdlib = { local = "lib/testnet/move-stdlib" }
# Sui = { local = "lib/testnet/Sui" }
suins = { local = "lib/testnet/suins" }

[dev-dependencies]

[dev-addresses]
